---
# Supply a valid jito block engine cluster
# testnet, mainnet
cluster: mainnet

# Supply a valid jito block engine location
# mainnet: amsterdam, frankfurt, ny, tokyo
# testnet: dallas, ny
location: "ny"

# commission in basis points. 100 bps = 1%
commission-bps: 800

# optional. sends metricss to solana's public influx. encouraged to set true since its helps labs and others debug
# if something is wrong with your validator
metrics: true
org_name: "jito-foundation"
repo_name: "jito-solana"
repo_dir: "jito-solana"
repo_version: "v1.13.6-jito"
