- name: Install a list of packages
  become: true
  become_user: root
  apt:
    update_cache: yes
    pkg:
    - build-essential
    - pkg-config
    - libudev-dev
    - cmake
    - libclang-dev
    - libssl-dev
    - gparted
    - nload
    - python3-pip
    - net-tools
    - logind
    - curl
    - git
    - chrony
    - htop
    - acl
      
- name: some python utils
  become: true
  become_user: solana
  ansible.builtin.pip:
    name:
      - tqdm
      - requests
      - pynacl
      - base58
    executable: pip3
      
- name: check if cargo is installed
  become: true
  become_user: solana
  become_method: sudo
  shell: test -f /home/solana/.cargo/env && source /home/solana/.cargo/env && command -v cargo
  args:
    executable: /bin/bash
  register: cargo_exists
  ignore_errors: yes

- name: Download Installer
  when: cargo_exists is failed
  become: true
  become_user: solana
  become_method: sudo
  get_url:
    url: https://sh.rustup.rs
    dest: /tmp/sh.rustup.rs
    mode: '0755'
    force: 'yes'

- name: install rust/cargo
  become: true
  become_user: solana
  become_method: sudo
  when: cargo_exists is failed
  shell: /tmp/sh.rustup.rs -y
  args:
    executable: /bin/bash

- name: Add Docker GPG apt Key
  become: true
  become_user: root
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  become: true
  become_user: root
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable
    state: present

- name: Update apt and install docker-ce
  become: true
  become_user: root
  apt:
    name: docker-ce
    state: latest
    update_cache: true

- name: Install Docker Module for Python
  become: true
  become_user: root
  pip:
    name: docker
